# Generated by Django 4.2.13 on 2024-06-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
